version: '2'
services:
  web:
    image: chernyshov/filesystem
    ports:
      - "8080:8080"
    volumes:
      - ./target/FileSystemTask-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war
      - ./target/FileSystemTask-1.0-SNAPSHOT:/usr/local/tomcat/webapps/ROOT